Algoritmo "AULA 01"
// Disciplina   : [Criação de Aplicações e Sistemas]
// Professor   : Franklin Portela
// Descrição   : Imprimi uma frase
// Autor(a)    : Arthur Do nascimento silva
// R.A         : 2216379

Var
// Seção de Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

Escreval ("O que você viverá amanhã, é fruto do que você escolhe hoje")

Fimalgoritmo