Algoritmo "NUMMAIOR"

Var
// Seção de Declarações das variáveis 

num1,num2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva (" Digite o primeiro número:")
leia(num1)
Escreva (" Digite o segundo número:")
leia(num2)
Se (num1 < num2) então
 Escreva (" O número maior é:",num2)
Senao
 Escreval ("Primeiro número digitado:",num1)
 Escreval ("Segundo número digitado:",num2)
fimse

Fimalgoritmo